#let table_experiment_params() = table(
  columns: 2,
  align: (left, left),
  table.header([Parametras], [Reikšmė]),
  table.cell(colspan: 2)[#text(weight: "semibold")[Algoritmo parametrai]],
  [nbGranular (granuliarumo parametras)], [20],
  [mu (min populiacijos dydis)], [25],
  [lambda (generacijos dydis)], [40],
  [nbElite (elitiniai individai)], [4],
  [nbClose (artimiausi individai)], [5],
  [nbIterPenaltyManagement (baudos parametrų atnaujinimo periodas)], [50],
  [targetFeasible (tikslinė įvykdomų sprendinių dalis)], [0.2],
  [penaltyIncrease / penaltyDecrease (baudos didinimo/mažinimo koeficientai)], [1.2 / 0.85],
  [useSwapStar (swap\* kaimynystės naudojimas)], [1 (naudojama, kai pateiktos koordinatės)],
  table.cell(colspan: 2)[#text(weight: "semibold")[Vykdymo parametrai]],
  [nbIter (iteracijų limitas)], [0 (iteracijų limitas netaikomas)],
  [$T_"max"$ (laiko limitas)], [$n dot 24/100$ s],
  [Sėklos (atsitiktinių skaičių generatoriaus pradinės reikšmės)], [1-5],
  [Gijų skaičius $p$ (paralelizavimo lygis)], [1, 2, 4, 8, 16],
  [Traces (progreso fiksavimo žingsnis)], [kas 1% laiko limito (wall-clock)],
)
