// #let table_parallel_compare() = table(
//   columns: 3,
//   align: (left, left, left),
//   table.header(
//     [Šaltinis],
//     [Lygiagretinimo schema],
//     [Rezultatas (metrika)],
//   ),
//   [@muniasamy2023Effect],
//   [ParMDS, OpenMP (CPU, iki 40 gijų)],
//   [Vid. greitėjimas: 9x vs SeqMDS, 36x vs Base1 (GPU), 1189x vs Base2 (GPU).],
//   [@yelmewad2021Parall],
//   [GPU vietinė paieška (route-/customer-level)],
//   [Customer-level greitėjimas iki 147.19x; route-level kai kur lėtesnis.],
//   [@lei2025Speedi],
//   [Tenzorinė GPU akceleracija vietinei paieškai],
//   [1000 mazgų CVRP ~50x; inter-route operatoriams ~2-60x.],
//   [@stadtler2023parallel],
//   [HGS CVRPPD + MPI + CUDA],
//   [greitėjimas 0.61x (50 porų) iki 4.61x (10k porų).],
//   [@jamshidi2025A_Para],
//   [PHGS (salų modelis, OpenMP CPU)],
//   [Sprendinių kokybės santykis ~1.8 galutiniame taške; greitėjimo skaičių nepateikia.],
//   [Šis darbas],
//   [HGS-CVRP vietinės paieškos lygiagretinimas (2–16 gijų)],
//   [$g dot =1.0%$: S_p P50 1.13-1.99, E_p P50 0.57-0.12 (2-16 gijos).],
// )
