direction: right

A: "START\nParameter initialization"
B: "INITIALISE INDIVIDUALS\nApply Clarke-Wright to generate individuals"
C: "POPULATION\nFeasible Solutions"
D: "Stop?" {
  shape: diamond
}
E: "END\nReturn the best solution"
F: "SELECTION\nBinary Tournament"
G: "CROSSOVER\nOrdered Crossover OX"
H: "LOCAL SEARCH\nRoute Improvement (RI)"
I: "INSERTION\nInsert feasible solutions into the population"

A -> B
B -> C
C -> D
D -> E: Yes
D -> F: No
F -> G
G -> H
H -> I
I -> C
