graph TD

    A[START <br> Parameter initialization] --> B["INITIALISE INDIVIDUALS <br> Apply Clarke-Wright to generate individuals"]

    B --> C["POPULATION <br> Feasible Solutions"]

    C --> D{Stop?}

    D -- Yes --> E[END <br> Return the best solution]

    D -- No --> F["SELECTION <br> Binary Tournament"]

    F --> G["CROSSOVER <br> Ordered Crossover OX"]

    G --> H["LOCAL SEARCH <br> Route Improvement (RI)"]

    H --> I["INSERTION <br> Insert feasible solutions into the population"]

    I --> C
